export const metadata = {
  title: 'Next.js latest',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body style={{backgroundColor:'#2196f3'}}>{children}</body>
    </html>
  )
}
